name: Docker Image CI
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        uses: elgohr/Publish-Docker-Github-Action@v5
        env:
          REACT_APP_SENTRY_DSN: https://353992084b0d40cb9a6a64292482d90e@sentry.io/5172565
          REACT_APP_API_ENDPOINT: https://api.beatcov-staging.com/
          REACT_APP_ANALYTICS_ID: UA-153695048-2
          NODE_ENV: development
          ENV: development
        with:
          name: beatcovid/website/website
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          buildargs: REACT_APP_SENTRY_DSN,REACT_APP_API_ENDPOINT,REACT_APP_ANALYTICS_ID,NODE_ENV,ENV,LOKALISE_API_TOKEN
          cache: true
