name: docker staging build
on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
      - name: Build the Docker image
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          REACT_APP_SENTRY_DSN: https://353992084b0d40cb9a6a64292482d90e@sentry.io/5172565
          REACT_APP_ANALYTICS_ID: UA-153695048-2
          ENV: production
        if: contains(github.ref, 'refs/tags/v')
        with:
          name: beatcovid/website/website:${{steps.vars.outputs.tag}}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          buildargs: REACT_APP_SENTRY_DSN,REACT_APP_ANALYTICS_ID,ENV,LOKALISE_API_TOKEN
